Data SIPPTEMP;
set SIPPTEMP;
	
		if  tbrstate=215 then Japan=1;
			else if tbrstate~=. then Japan=0;
		if  tbrstate=339 then DominicanRepublic=1;
			else if tbrstate~=. then DominicanRepublic=0;
		if  tbrstate=312 then ElSalvador=1;
			else if tbrstate~=. then ElSalvador=0;
*Natives;
		if tbrstate <100 & White=1 & tbrstate~=. then NativeWhite=1;
			else if tbrstate~=. then NativeWhite=0;
		if tbrstate<100 & Black=1 & tbrstate~=. then NativeBlack=1;
			else if tbrstate~=. then NativeBlack=0;
*Ethnicity variable for looping through proc means by ethnicity and Ethnicity Variable For Models;
	*China;
		if tbrstate=207 then do;
			Ethnicity1='Mainland Chinese';
			Ethnicity=1;
			MainlandChinese=1;
			end;
			else if tbrstate~=. then MainlandChinese=0;
	*HKTaiwan;
		if  tbrstate=209 | tbrstate=238 then do; 
			Ethnicity1='HK-Taiwan';
			Ethnicity=2;
			HKTaiwan=1;
			end;
			else if tbrstate~=. then HKTaiwan=0;
	*India;
		if  tbrstate=210 then do;
			Ethnicity1='Asian Indian';
			Ethnicity=3;
			AsianIndian=1;
			end;
			else if tbrstate~=. then AsianIndian=0;
	*European;
		if  tbrstate=>100 & tbrstate<200 then do;
			Ethnicity1='European';
			Ethnicity=13;
			European=1;
			end;
			else if tbrstate~=. then Europe=0;
	*Philipines;
		if tbrstate=231 then do;
			Ethnicity1='Phillipino';
			Ethnicity=14;
			Phillipino=1;
			end;
			else if tbrstate~=. then Phillipino=0;
	*Korea;
		if  tbrstate=217 then do;
			Ethnicity1='Korean';
			Ethnicity=15;
			Korean=1;
			end;
			else if tbrstate~=. then Korean=0;
	*Vietnam;
		if  tbrstate=242  then do;
			Ethnicity1='Vietnam';
			Ethnicity=16;
			Vietnam=1;
			end;
			else if tbrstate~=. then Vietnam=0;
	*Canada;
		if tbrstate=301 then do;
			Ethnicity1='Canada';
			Ethnicity=17;
			Canada=1;
			end;
			else if tbrstate~=. then Canada=0;
	*Africa;
*		if tbrstate>=400 & tbrstate<500 then do;
*			Ethnicity1='African';
*			Ethnicity=18;
*			African=1;
*			end;
*			else if tbrstate~=. then African=0;
	*Rest of Asia;
*		if  tbrstate=>200 & tbrstate<300 & AsianIndian~=1 & HKTaiwan~=1 & MainlandChinese~=1 & Phillipino~=1 & Korean~=1 & Vietnam~=1 then do;
*			Ethnicity1='Other Asian';
*			Ethnicity=4;
*			OtherAsian=1;
*			end;
*			else if tbrstate~=. then OtherAsian=0;
	*Native Asian;
		if  Asian=1 & tbrstate<100 & tbrstate~=. then do;
			Ethnicity1='Native Asian'; 
			Ethnicity=5;
			NativeAsian=1;
			end;
			else if tbrstate~=. then NativeAsian=0;
	*Mexico;
		if  tbrstate=315 then do;
			Ethnicity1='Mexican';
			Ethnicity=6;
			Mexican=1;
			end;
			else if tbrstate~=. then Mexican=0;
	*Cuba;
		if  tbrstate=337 then do; 
			Ethnicity1='Cuban';
			Ethnicity=7;
			Cuban=1;
			end;
			else if tbrstate~=. then Cuban=0;
	*Other Latino;
*		if  tbrstate=>300 & tbrstate<400 & tbrstate~=301 & Mexican~=1 & Cuban~=1 then do;
*			Ethnicity1='Other Latino';
*			Ethnicity=8;
*			OtherLatino=1;
*			end;
*			else if tbrstate~=. then OtherLatino=0;
	*Latino;
		if  Latino=1 & tbrstate<100 & tbrstate~=. then do;
			Ethnicity1='Native Latino';
			Ethnicity=9;
			NativeLatino=1;
			end;
			else if tbrstate~=. then NativeLatino=0;
	*Other immigrants;
		if  tbrstate=>100 & Ethnicity=. then do; 
			Ethnicity1='Other Immigrants';
			Ethnicity=10;
			OtherImmigrants=1;
			end;
			else if tbrstate~=. then OtherImmigrants=0;
	*Native Blacks;
		if  NativeBlack=1 then do; 
			Ethnicity1="Reference Category-Native Black";
			Ethnicity=11;
			NativeBlack=1;
			end;
			else if tbrstate~=. then NativeBlack=0;
	*Native White;
		if  NativeWhite=1 then do;
			Ethnicity1='Native White';
			Ethnicity=12;
			NativeWhite=1;
			end;
			else if tbrstate~=. then NativeWhite=0;
*		if  tbrstate=. then do;
*			Ethnicity1='Missing Ethnicity';
*			Ethnicity=13;
*			MissingEthnicity=1;
*			end;
*			else MissingEthnicity=0;
/*Create Region of origin Variables;
			if Ethnicity=1 |Ethnicity=2 |Ethnicity=3 | Ethnicity=4 then continent= "Asia";
			if Ethnicity=6 |Ethnicity=7 |Ethnicity=8 then continent="LatinAmerica";
			if Ethnicity=5 |Ethnicity=9 |Ethnicity=11 | Ethnicity=12 then continent="NorthAmerica";
			if Ethnicity=10 then continent="other";
*/
*Kill other continent variables;
*		if Ethnicity=4 |Ethnicity=8 then Ethnicity1='Other Immigrants';
*		if Ethnicity=4 |Ethnicity=8 then Ethnicity=10;

*	if tbrstate=215 then Ethnicity1="Japan";
*	if tbrstate=209 then Ethnicity1="Hong Kong";
*	if tbrstate=238 then Ethnicity1="Taiwan";
*	if tbrstate=200 then CentralAsia=1;
*	if tbrstate=234 then Ethnicity1="EastAsia";
*	if tbrstate=200 or tbrstate=202 or tbrstate=229 then Ethnicity1="SouthAsia";
	if tbrstate=205 or tbrstate=206 or tbrstate=211 or tbrstate=221 or tbrstate=224 or tbrstate=239 then Ethnicity1="SouthEastAsia";
	if tbrstate=212 or tbrstate=213 or tbrstate=214 or tbrstate=216 or tbrstate=222 or tbrstate=233 or tbrstate=237 or tbrstate=240 or tbrstate=252 or tbrstate=253 then Ethnicity1="WesternAsia";
	if tbrstate>309 and tbrstate<320 and tbrstate~=315 then Ethnicity1="CentralAmerica";
	if tbrstate>375 and tbrstate<390 then Ethnicity1="SouthAmerica";
	if tbrstate>337 and tbrstate<354 then Ethnicity1="Carribean";
run;

*No Native American variable makes these add up to about 99% of the population.;

*Save SIPP info;
data SIPP.SIPPTemp;
	set SIPPTemp;
run;

*Just sipp with net worth over 100000;
data richsipptemp;
set sipptemp;
if networth<100000 then delete;
run;




*Figure out which variables distinguish asian groups;
data richasiantemp;
set sipptemp;
if NativeAsian=0 & AsianIndian =0 then delete;
if networth<100000 then delete;
run;

*Figure out which variables distinguish latino groups;
data richlatinotemp;
set sipptemp;
if NativeLatino =0 & Mexican =0 & Cuban =0 then delete;
if networth<100000 then delete;
run;

*/exclude yearmarried and supportother for now due to low response rates;
proc logistic data=richlatinotemp;
 *model Cuban(event='1')  = Age Children Mortgages VehicleValue NumberCarOwned loggednetworth loggeddebt loggedassets loggedhomeequity loggedCheckingValue loggedSavingsPlanValue loggedStockValue loggedIraValue loggedLifeInsuranceValue loggedOtherRealEstateValue loggedBusinessValue loggedOtherAssetValue loggedSecuredDebtValue loggedHomeDebt loggedCreditCardDebtValue loggedCarDebt Female Education Married StockMutual InterestBank IRAor401k Unemployed OwnCar HomeOwner jointsavings RentsProperty businessowner ownmotorcycle ownrv ownothervehicle ownnoncar studentloan supportchild supportother evermilitary OutsideKids Widowed Divorced Separated DistantSpouse HouseHoldSize spouse grandchild parent sibling otherrelative fosterchild partner housemate boarder other anyincref anyincspouse loggedincref loggedincspouse salaryincome EnglishProficiency ;
class Race Education WorkStatus SWorkStatus Marital;
model Cuban(event='1')  = age	boarder	children	evermilitary	female	grandchild	HomeOwner	HouseHoldSize	InterestBank	IRAor401k	loggedassets	loggeddebt loggedCarDebt	loggedCreditCardDebtValue	loggedHomeDebt	loggedIraValue	loggedLifeInsuranceValue	loggedOtherRealEstateValue	loggedsalaryincome	loggedSavingsPlanValue	loggedSecuredDebtValue	loggedVehicleValue	loggedyearsatjob	Mortgages	NumberCarOwned	ownmotorcycle	ownnoncar	ownrv	parent	StockMutual	supportchild	year WorkStatus SWorkStatus Marital Race Education EnglishProficiency
/selection=backward slstay=.1;
 run;*/;

*RentsProperty loggedotherassetvalue otherrelative

 *proc logistic data=richasiantemp;
* model AsianIndian(event='1')  = age	boarder	children	DistantSpouse	Divorced	evermilitary	female	fulltime	grandchild	homemaker	HomeOwner	HouseHoldSize	InterestBank	IRAor401k	loggedassets	loggedCarDebt	loggedCreditCardDebtValue	loggeddebt	loggedHomeDebt	loggedIraValue	loggedLifeInsuranceValue	loggednetworth	loggedOtherAssetValue	loggedOtherRealEstateValue	loggedsalaryincome	loggedSavingsPlanValue	loggedSecuredDebtValue	loggedVehicleValue	loggedyearsatjob	Married	Mortgages	NeverMarried	NumberCarOwned	otherrelative	ownmotorcycle	ownnoncar	ownrv	parent	parttime	RentsProperty	retired	Separated	Sfulltime	Shomemaker	Sparttime	spouse	Sretired	StockMutual	supportchild	Unemployed	year	Race	Education EnglishProficiency;
* run;*/;

proc freq data=richsipptemp; tables ethnicity1; run;
